import Link from "next/link";
import { fetchFeed, fetchRepoStats } from "@/lib/github";
import { getDispatch, getEnv } from "@/lib/kv";
import { getFacts } from "@/lib/facts";
import { Ticker } from "@/components/ticker";
import { StatGrid } from "@/components/stat-grid";
import { Seal } from "@/components/seal";
import { MermaidDiagram } from "@/components/mermaid-diagram";
import type { CuratedDispatch, FeedItem, RepoStats } from "@/lib/types";

export const revalidate = 1800;

const FALLBACK_STATS: RepoStats = {
  stars: 0,
  forks: 0,
  openIssues: 0,
  openPulls: 0,
  contributors: 98,
  fetchedAt: new Date().toISOString(),
};

const FALLBACK_DISPATCH_EN: CuratedDispatch = {
  generatedAt: new Date().toISOString(),
  headline: "Quiet release week — install paths and contributor guides up to date.",
  summary:
    "This dispatch is regenerated by DeepSeek V4-Flash on a six-hour cron. Until the cron fills in fresh repo activity, the static links below are the best starting points.",
  highlights: [
    { title: "Install", href: "/install", tag: "shipped", blurb: "npm, Cargo, Homebrew, or a direct download." },
    { title: "Open issues", href: "https://github.com/Hmbown/CodeWhale/issues", tag: "opened", blurb: "Start with anything labelled good first issue." },
    { title: "Roadmap", href: "/roadmap", tag: "discussion", blurb: "What is confirmed, what is being weighed, what is ruled out." },
  ],
  movers: [],
};

const FALLBACK_DISPATCH_ZH: CuratedDispatch = {
  generatedAt: new Date().toISOString(),
  headline: "本周发布平稳——安装路径和贡献指南已同步。",
  summary:
    "本「今日要闻」由 DeepSeek V4-Flash 每六小时重新生成。在 cron 写入真实仓库动态之前，下面的固定链接是最实用的入口。",
  highlights: [
    { title: "安装", href: "/zh/install", tag: "shipped", blurb: "npm、Cargo、Homebrew，或直接下载。" },
    { title: "开放议题", href: "https://github.com/Hmbown/CodeWhale/issues", tag: "opened", blurb: "从 good first issue 标签开始。" },
    { title: "路线图", href: "/zh/roadmap", tag: "discussion", blurb: "已确认、审议中、以及已排除的功能。" },
  ],
  movers: [],
};

export default async function HomePage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const isZh = locale === "zh";
  const env = await getEnv();
  const facts = await getFacts();

  let stats: RepoStats = FALLBACK_STATS;
  let feed: FeedItem[] = [];
  let dispatch: CuratedDispatch = isZh ? FALLBACK_DISPATCH_ZH : FALLBACK_DISPATCH_EN;

  try {
    [stats, feed] = await Promise.all([
      fetchRepoStats(env.GITHUB_TOKEN),
      fetchFeed(env.GITHUB_TOKEN, 12),
    ]);
  } catch (e) {
    console.error("github fetch failed", e);
  }

  try {
    const cached = await getDispatch();
    if (cached) dispatch = cached;
  } catch {
    /* keep fallback */
  }

  const highlights = isZh && dispatch.highlightsZh ? dispatch.highlightsZh : dispatch.highlights;

  return (
    <>
      <Ticker items={feed} />

      {/* HERO */}
      <section className="relative">
        <div className="mx-auto max-w-[1400px] px-4 sm:px-6 pt-10 sm:pt-14 pb-12 grid lg:grid-cols-12 gap-10">
          <div className="lg:col-span-7">
            <div className="mb-6">
              <span className="pill pill-hot">DeepSeek V4 · 1M context</span>
            </div>

            <h1 className="font-display tracking-crisp">
              {isZh
                ? "DeepSeek V4 的最强智能体运行框架。"
                : "The most agentic harness for DeepSeek V4."}
            </h1>

            <p className="mt-6 text-lg text-ink-soft leading-relaxed max-w-2xl">
              <span className="font-cjk text-indigo font-semibold">CodeWhale</span>
              {isZh
                ? " 是围绕 DeepSeek V4 Pro 和 Flash 构建的运行框架。规则、工具、证据和反馈循环——帮助模型持续工作，并且不断进步。DeepSeek V4 参与了部分编写。更好的框架让 V4 更有效，更有效的 V4 又让框架变得更好——这是个正向循环。"
                : " is a harness built around DeepSeek V4 Pro and Flash. Rules, tools, evidence, and feedback loops that help the model keep working — and keep improving. DeepSeek V4 helped write parts of it. A better harness makes V4 more effective, and a more effective V4 makes the harness better — it loops."}
            </p>

            <div className="mt-8 flex flex-wrap items-stretch sm:items-center gap-3">
              <Link
                href={isZh ? "/zh/install" : "/install"}
                className="flex-1 sm:flex-none text-center px-5 py-3 bg-ink text-paper font-mono text-sm uppercase tracking-wider hover:bg-indigo transition-colors"
              >
                {isZh ? "立即安装 →" : "Install →"}
              </Link>
              <Link
                href="https://github.com/Hmbown/CodeWhale"
                className="flex-1 sm:flex-none text-center px-5 py-3 hairline-t hairline-b hairline-l hairline-r font-mono text-sm uppercase tracking-wider hover:bg-paper-deep transition-colors"
              >
                ★ GitHub
              </Link>
              <Link
                href={isZh ? "/zh/docs" : "/docs"}
                className="px-5 py-3 font-mono text-sm uppercase tracking-wider text-ink-mute hover:text-indigo transition-colors"
              >
                {isZh ? "阅读文档" : "Docs"}
              </Link>
            </div>

            <div className="mt-6 flex items-center gap-4 text-xs font-mono text-ink-mute flex-wrap">
              <span>{isZh ? "独立维护者 Hmbown" : "Maintained by Hmbown"}</span>
              <span className="hidden sm:inline">·</span>
              <span>{facts.version ?? "v0.8.x"}</span>
              <span className="hidden sm:inline">·</span>
              <span>{facts.providers.length} providers</span>
            </div>
          </div>

          <div className="lg:col-span-5">
            <div className="hairline-t hairline-b hairline-l hairline-r bg-paper p-5 relative">
              <div className="absolute -top-3 left-4 bg-paper px-2 eyebrow">
                {isZh ? "一行安装" : "one-line install"}
              </div>
              <pre className="code-block mt-2">
                {isZh ? (
                  <>
                    <span className="comment"># npm（推荐，无需 Rust 工具链）</span>{"\n"}
                    <span className="prompt">$</span> npm install -g codewhale{"\n"}
                    <span className="prompt">$</span> codewhale{"\n"}
                    <br />
                    <span className="comment"># Cargo / Homebrew / 直接下载请见</span>{"\n"}
                    <span className="comment"># <span className="key">/install</span></span>
                  </>
                ) : (
                  <>
                    <span className="comment"># npm — no Rust toolchain required</span>{"\n"}
                    <span className="prompt">$</span> npm install -g codewhale{"\n"}
                    <span className="prompt">$</span> codewhale{"\n"}
                    <br />
                    <span className="comment"># Cargo / Homebrew / direct download:</span>{"\n"}
                    <span className="comment"># <span className="key">/install</span></span>
                  </>
                )}
              </pre>
              <div className="mt-3 flex items-center justify-between text-[0.7rem] font-mono text-ink-mute">
                <span>{isZh ? "需要 Node 或 Rust 1.88+" : "needs Node or Rust 1.88+"}</span>
                <Link href={isZh ? "/zh/install" : "/install"} className="text-indigo hover:underline">{isZh ? "其他方式 →" : "other ways →"}</Link>
              </div>
            </div>
          </div>
        </div>
      </section>

      <StatGrid stats={stats} />

      {/* WHAT IT IS */}
      <section className="mx-auto max-w-[1400px] px-6 py-16">
        <div className="flex items-baseline gap-4 mb-8 hairline-b pb-4">
          <Seal char="是" />
          <h2 className="font-display">
            {isZh ? "它到底是什么" : "What it actually is"}
          </h2>
        </div>

        <div className="grid md:grid-cols-3 gap-0 col-rule hairline-t hairline-b">
          {isZh ? (
            <>
              <div className="p-6">
                <div className="eyebrow mb-3">01 · 宪政层级</div>
                <h3 className="font-display text-xl mb-3">用户意图高于一切</h3>
                <p className="text-sm text-ink-soft leading-[1.9]">
                  实时证据高于假设。验证高于自信。清晰的权威链让模型无需猜测该服从哪条指令。
                </p>
              </div>
              <div className="p-6">
                <div className="eyebrow mb-3">02 · 反馈驱动</div>
                <h3 className="font-display text-xl mb-3">失败是信号，不是终点</h3>
                <p className="text-sm text-ink-soft leading-[1.9]">
                  失败的命令、失败的测试、LSP 错误。框架让失败可读。每一次节拍都是模型可以调谐的信息，逐轮迭代。
                </p>
              </div>
              <div className="p-6">
                <div className="eyebrow mb-3">03 · 自我修正</div>
                <h3 className="font-display text-xl mb-3">恢复内建于环境</h3>
                <p className="text-sm text-ink-soft leading-[1.9]">
                  子智能体、回滚、会话分叉、交接。模型不需要一次就全对。恢复机制从底层支持试错。
                </p>
              </div>
            </>
          ) : (
            <>
              <div className="p-6">
                <div className="eyebrow mb-3">01 · constitutional</div>
                <h3 className="font-display text-xl mb-3">User intent above everything</h3>
                <p className="text-sm text-ink-soft leading-relaxed">
                  Live evidence above assumptions. Verification above confidence. A clear chain of authority so the model never guesses which instruction to follow.
                </p>
              </div>
              <div className="p-6">
                <div className="eyebrow mb-3">02 · feedback-driven</div>
                <h3 className="font-display text-xl mb-3">Failure is signal, not a dead end</h3>
                <p className="text-sm text-ink-soft leading-relaxed">
                  Failed commands, failing tests, LSP errors. The harness makes failure legible. Each beat is information the model can tune against, turn after turn.
                </p>
              </div>
              <div className="p-6">
                <div className="eyebrow mb-3">03 · self-correcting</div>
                <h3 className="font-display text-xl mb-3">Recovery built into the environment</h3>
                <p className="text-sm text-ink-soft leading-relaxed">
                  Sub-agents, rollback, session forks, handoffs. The model doesn't have to get everything right the first time. Recovery is built into the environment.
                </p>
              </div>
            </>
          )}
        </div>

        <div className="mt-8 hairline-t pt-6 flex flex-wrap items-baseline gap-x-6 gap-y-3">
          <div className="eyebrow shrink-0">{isZh ? "内建提供商" : "Built-in providers"}</div>
          <div className="flex flex-wrap gap-2">
            {facts.providers.map((p) => (
              <span key={p.id} className="font-mono text-xs px-2 py-1 hairline-t hairline-b hairline-l hairline-r text-ink-soft">
                {p.label}
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* 100-TO-1 MODEL */}
      <section className="bg-paper-deep hairline-t hairline-b">
        <div className="mx-auto max-w-[1400px] px-6 py-16">
          <div className="grid lg:grid-cols-12 gap-10 items-start">
            <div className="lg:col-span-5">
              <div className="flex items-baseline gap-4 mb-4">
                <Seal char="百" />
                <div className="eyebrow">{isZh ? "100:1 模型" : "100-to-1 model"}</div>
              </div>
              <h2 className="font-display">
                {isZh ? "递归自我改进的开源智能体框架" : "A recursive harness, modelled at 100-to-1"}
              </h2>
              <p className={`mt-5 text-ink-soft ${isZh ? "leading-[1.9] tracking-wide" : "leading-relaxed"}`}>
                {isZh
                  ? "1948 年，Ralph Bown 用 100:1 的晶体管模型，把微小的结构讲清楚。CodeWhale 借用同样的形状：一个清晰提示词，把 DeepSeek V4 Pro 的缓存注意力、工具调用与子智能体凝结为一个可审查的小补丁。"
                  : "In 1948, Ralph Bown used a 100-to-1 model of the transistor to make a tiny structure legible. CodeWhale uses the same shape: one clear prompt turns DeepSeek V4 Pro's cached attention, tool use, and sub-agents into one small, reviewable patch."}
              </p>
              <p className={`mt-4 text-sm text-ink-mute ${isZh ? "leading-[1.9] tracking-wide" : "leading-relaxed"}`}>
                {isZh
                  ? "100:1 不是性能基准，而是贡献形状：一个提示词、许多智能体小时、一个小补丁、一次维护者审查。"
                  : "100-to-1 is not a throughput benchmark. It is a contribution shape: one prompt, many agent-hours, one small patch, one maintainer review."}
              </p>
              <p className={`mt-4 text-sm text-ink-soft ${isZh ? "leading-[1.9] tracking-wide" : "leading-relaxed"}`}>
                {isZh
                  ? "框架承担了繁重工作：宪政提示、结构化信任、反馈循环和跨会话存活的交接。模型可以专注于任务本身。因为 DeepSeek V4 参与构建了这套框架，每一次改进都让 V4 在其中变得更有效——这让下一次改进变得更容易。"
                  : "The harness does the heavy lifting: constitutional prompts, structured trust, feedback loops, and handoffs that survive the session. The model is free to focus on the task. And because DeepSeek V4 helped build this harness, each improvement makes V4 more effective within it — which makes the next improvement easier."}
              </p>
              <div className="mt-6 flex flex-wrap gap-3">
                <Link href={isZh ? "/zh/contribute#recursive-harness" : "/contribute#recursive-harness"} className="px-4 py-2 bg-ink text-paper font-mono text-sm uppercase tracking-wider hover:bg-indigo transition-colors">
                  {isZh ? "运行提示词 →" : "Run the prompt →"}
                </Link>
                <Link href="https://api-docs.deepseek.com/quick_start/pricing" className="px-4 py-2 font-mono text-sm uppercase tracking-wider text-ink-mute hover:text-indigo transition-colors">
                  {isZh ? "DeepSeek 价格 →" : "DeepSeek pricing →"}
                </Link>
              </div>
            </div>

            <div className="lg:col-span-7 hairline-t hairline-b hairline-l hairline-r bg-paper">
              <div className="bg-ink text-paper px-4 py-3 flex items-center justify-between gap-4">
                <div className="font-mono text-sm uppercase tracking-widest">CodeWhale / 100:1</div>
                <div className="font-cjk text-sm text-paper-deep/80">{isZh ? "演示模型" : "demonstration model"}</div>
              </div>
              <div className="grid sm:grid-cols-2 gap-0 col-rule">
                {(isZh
                  ? [
                      { n: "01", t: "输入", d: "贡献者在 fork 中运行 CodeWhale，并给出递归改进提示词。" },
                      { n: "02", t: "相互作用", d: "DeepSeek V4 Pro 读取代码库、调用工具、协调子智能体，前缀缓存让长程注意力保持低成本。" },
                      { n: "03", t: "输出", d: "智能体返回一个可复现、可测试、可审查的小补丁。" },
                      { n: "04", t: "反馈", d: "维护者审查、合并、发布。下一轮在更好的框架上开始。" },
                    ]
                  : [
                      { n: "01", t: "Input", d: "A contributor runs CodeWhale in a fork with the recursive harness prompt." },
                      { n: "02", t: "Interaction", d: "DeepSeek V4 Pro reads the repo, uses tools, coordinates sub-agents; prefix caching keeps long attention cheap." },
                      { n: "03", t: "Output", d: "The agent returns one reproducible, tested, reviewable patch." },
                      { n: "04", t: "Feedback", d: "The maintainer reviews, lands, releases. The next run starts from a better harness." },
                    ]
                ).map((item) => (
                  <div key={item.n} className="p-5">
                    <div className="font-mono text-[0.7rem] text-indigo uppercase tracking-widest mb-2">{item.n}</div>
                    <h3 className="font-display text-lg mb-2">{item.t}</h3>
                    <p className={`text-sm text-ink-soft ${isZh ? "leading-[1.9] tracking-wide" : "leading-relaxed"}`}>
                      {item.d}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* HOW IT WORKS */}
      <section className="mx-auto max-w-[1400px] px-6 py-16">
        <div className="flex items-baseline gap-4 mb-8 hairline-b pb-4">
          <Seal char="作" />
          <h2 className="font-display">
            {isZh ? "运作方式" : "How it works"}
          </h2>
        </div>

        <div className="hairline-t hairline-b hairline-l hairline-r bg-paper p-4 sm:p-8">
          <MermaidDiagram
            label={isZh ? "CodeWhale 运作方式示意图" : "CodeWhale architecture diagram"}
            chart={
              isZh
                ? `flowchart TD
    A["用户输入<br/>(TUI · ratatui)"] -->|Op channel| B["Engine<br/>turn loop + tools"]
    B -->|HTTPS / SSE| C["DeepSeek API<br/>V4 family"]
    C -->|stream events| B
    B -->|tool call| T["read_file · edit_file · grep<br/>apply_patch · exec_shell<br/>mcp_&lt;server&gt;_&lt;tool&gt;"]
    T -->|approval Y/N| P["审批对话框<br/>approval dialog"]
    P --> B
    T -->|exec| S["沙箱<br/>seatbelt · landlock · win32"]
    classDef accent fill:#e9eefe,stroke:#0e0e10,stroke-width:1px;
    classDef api fill:#0e0e10,stroke:#0e0e10,color:#ffffff;
    class C api;
    class T,P,S accent;`
                : `flowchart TD
    A["You type<br/>(TUI · ratatui)"] -->|Op channel| B["Engine<br/>turn loop + tools"]
    B -->|HTTPS / SSE| C["DeepSeek API<br/>V4 family"]
    C -->|stream events| B
    B -->|tool call| T["read_file · edit_file · grep<br/>apply_patch · exec_shell<br/>mcp_&lt;server&gt;_&lt;tool&gt;"]
    T -->|approval Y/N| P["Approval<br/>dialog"]
    P --> B
    T -->|exec| S["Sandbox<br/>seatbelt · landlock · win32"]
    classDef accent fill:#e9eefe,stroke:#0e0e10,stroke-width:1px;
    classDef api fill:#0e0e10,stroke:#0e0e10,color:#ffffff;
    class C api;
    class T,P,S accent;`
            }
          />
        </div>
      </section>

      {/* TODAY'S DISPATCH — slim editorial column */}
      <section className="bg-paper-deep hairline-t hairline-b">
        <div className="mx-auto max-w-[1400px] px-6 py-14">
          <div className="flex items-end justify-between mb-6 hairline-b pb-4 flex-wrap gap-3">
            <div>
              <div className="eyebrow mb-2">{isZh ? "今日要闻" : "Today's Dispatch"}</div>
              <div className="font-mono text-sm tabular text-ink-mute">
                {new Date(dispatch.generatedAt).toISOString().slice(0, 10)}
              </div>
            </div>
            <div className="font-mono text-xs text-ink-mute">DeepSeek V4-Flash · 6h cron</div>
          </div>

          <article className="grid lg:grid-cols-12 gap-x-10 gap-y-6 max-w-[1100px]">
            <h3 className="lg:col-span-12 font-display text-2xl sm:text-3xl leading-tight">
              {isZh && dispatch.headlineZh ? dispatch.headlineZh : dispatch.headline}
            </h3>
            <p className={`lg:col-span-7 text-ink-soft ${isZh ? "leading-[1.9] tracking-wide" : "leading-relaxed"}`}>
              {isZh && dispatch.summaryZh ? dispatch.summaryZh : dispatch.summary}
            </p>
            <ul className="lg:col-span-5 space-y-3">
              {highlights.slice(0, 3).map((h, i) => (
                <li key={i} className="flex items-baseline gap-3">
                  <span className="font-mono text-[0.66rem] text-indigo uppercase tracking-widest w-16 shrink-0">
                    {h.tag}
                  </span>
                  <div>
                    <Link href={h.href} className="body-link font-display text-base leading-snug">
                      {h.title}
                    </Link>
                    <p className={`text-sm text-ink-soft mt-0.5 ${isZh ? "leading-[1.8]" : ""}`}>{h.blurb}</p>
                  </div>
                </li>
              ))}
            </ul>
          </article>

          <div className="mt-8 hairline-t pt-4">
            <Link href={isZh ? "/zh/feed" : "/feed"} className="font-mono text-xs uppercase tracking-wider text-indigo hover:underline">
              {isZh ? "全部活动 →" : "All activity →"}
            </Link>
          </div>
        </div>
      </section>

      {/* JOIN IN */}
      <section className="bg-ink text-paper">
        <div className="mx-auto max-w-[1400px] px-6 py-16 grid lg:grid-cols-12 gap-10 items-center">
          <div className="lg:col-span-8">
            <div className="eyebrow text-paper-deep/70 mb-3">{isZh ? "加入" : "Join in"}</div>
            <h2 className="font-display text-paper text-4xl leading-tight">
              {isZh ? "小项目。你的每个补丁都重要。" : "A small project. Your patch matters."}
            </h2>
            <p className={`mt-5 text-paper-deep/80 max-w-2xl ${isZh ? "leading-[1.9]" : "leading-relaxed"}`}>
              {isZh
                ? "无 CLA，无赞助商优先通道。维护者亲自阅读每一条内容，议题公开分类，版本从 main 分支发布。"
                : "No CLA. No sponsor lockouts. The maintainer reads everything personally, issues are triaged in the open, and releases cut from main."}
            </p>
            <div className="mt-6 flex flex-wrap items-center gap-3">
              <Link
                href="https://github.com/Hmbown/CodeWhale"
                className="px-4 py-2 hairline-t hairline-b hairline-l hairline-r border-white/20 text-paper font-mono text-sm hover:bg-white/10 transition-colors"
              >
                ★ {isZh ? "Star on GitHub" : "Star on GitHub"}
              </Link>
              <Link
                href={isZh ? "/zh/contribute" : "/contribute"}
                className="px-4 py-2 font-mono text-sm text-paper-deep/80 hover:text-paper transition-colors"
              >
                {isZh ? "参与贡献 →" : "Contribute →"}
              </Link>
            </div>
          </div>

          <div className="lg:col-span-4 font-mono text-sm text-paper-deep/80 space-y-2">
            <div className="flex justify-between hairline-b border-white/15 pb-2">
              <span className="uppercase tracking-widest text-[0.66rem] text-paper-deep/60">{isZh ? "版本" : "version"}</span>
              <span className="tabular text-paper">{facts.version ?? "v0.8.x"}</span>
            </div>
            <div className="flex justify-between hairline-b border-white/15 pb-2">
              <span className="uppercase tracking-widest text-[0.66rem] text-paper-deep/60">{isZh ? "提供商" : "providers"}</span>
              <span className="tabular text-paper">{facts.providers.length}</span>
            </div>
            <div className="flex justify-between hairline-b border-white/15 pb-2">
              <span className="uppercase tracking-widest text-[0.66rem] text-paper-deep/60">{isZh ? "许可证" : "license"}</span>
              <span className="text-paper">{facts.license ?? "MIT"}</span>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
