set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_C_COMPILER "$ENV{OHOS_NDK_HOME}/llvm/bin/clang")
set(CMAKE_CXX_COMPILER "$ENV{OHOS_NDK_HOME}/llvm/bin/clang++")
set(CMAKE_FIND_ROOT_PATH "$ENV{OHOS_NDK_HOME}/sysroot")
set(CMAKE_SYSROOT "$ENV{OHOS_NDK_HOME}/sysroot")
set(CMAKE_C_FLAGS "--target=aarch64-linux-ohos -D__MUSL__" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "--target=aarch64-linux-ohos -D__MUSL__" CACHE STRING "" FORCE)
set(CMAKE_EXE_LINKER_FLAGS "--target=aarch64-linux-ohos -fuse-ld=lld --sysroot=$ENV{OHOS_NDK_HOME}/sysroot -L$ENV{OHOS_NDK_HOME}/sysroot/usr/lib/aarch64-linux-ohos" CACHE STRING "" FORCE)
set(CMAKE_SHARED_LINKER_FLAGS "--target=aarch64-linux-ohos -fuse-ld=lld --sysroot=$ENV{OHOS_NDK_HOME}/sysroot -L$ENV{OHOS_NDK_HOME}/sysroot/usr/lib/aarch64-linux-ohos" CACHE STRING "" FORCE)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
